name: Manually triggered workflow
on:
  push:
    branches:
      - main
  pull-request:

concurrency:
  group: ${{ github.workflow }}

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        if: |
          github.repository_owner == 'wpilibsuite' &&
          github.ref == 'refs/heads/main'
        run: sleep 2m