name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      id:
        description: 'PR ID'
        required: true
        default: 'main'

concurrency: 
  group: ${{ github.workflow }}

jobs:
  run_main:
    if: github.repository_owner == 'Piphi5' && github.event.inputs.id == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          $CONDA/bin/conda env update --file environment.yml --name base
      - name: Setup Earth Engine credentials
        run: |
          $CONDA/bin/python "EE Testing/create_ee_json.py" ${{ secrets.EE_JSON }}
          $CONDA/bin/python "EE Testing/test.py"
  run_pr:
    if: github.repository_owner == 'Piphi5' && github.event.inputs.id != 'main' 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.inputs.id }}/head
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          $CONDA/bin/conda env update --file environment.yml --name base
      - name: Setup Earth Engine credentials
        run: |
          $CONDA/bin/python "EE Testing/create_ee_json.py" ${{ secrets.EE_JSON }}
          $CONDA/bin/python "EE Testing/test.py"