name: Manually triggered workflow
on:
  workflow_dispatch

concurrency: 
  group: ${{ github.workflow }}

jobs:
  say_hello:
    if: github.repository_owner == 'Piphi5'
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: sleep 2m